spring:
  application:
    name: api-digitalmailsender

# OpenAPI
openapi:
  name: ${spring.application.name}
  title: Digital Mail Sender
  version: '@project.version@'

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: always

integration:
  # Skatteverket integration
  skatteverket:
    # Max size in bytes for the outgoing SOAP-envelope (2MB)
    message-max-size: 2097152
    # Which suppliers we support
    supported-suppliers:
      - kivra
      - minmyndighetspost
      - billo
      - fortnox

# Logging
logbook:
  body-filters:
    # Exclude base64-encoded content from incoming requests.
    jsonPath:
      - key: '$.bodyInformation.body'
        value : '[base64]'
      - key: '$.attachments[*].body'
        value : '[base64]'
    # Exclude base64-encoded content from traffic to/from skatteverket
    xPath:
      - key: '//*[contains(local-name(), "X509Certificate")]'
        value: '[base64]'
      - key: '\\//SignatureValue/text()'
        value: '[base64]'
      - key: '\\//X509Certificate/text()'
        value: '[base64]'
