spring:
  application:
    name: api-digitalmailsender

# OpenAPI
openapi:
  name: ${spring.application.name}
  title: Digital Mail Sender
  version: '@project.version@'

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: always

integration:
  # Skatteverket integration
  skatteverket:
    # Max size in bytes for the outgoing SOAP-envelope (2MB)
    message-max-size: 2097152
    # Which suppliers we support
    supported-suppliers:
      - kivra
      - minmyndighetspost
      - billo
      - fortnox

# Logging
logbook:
  exclusionfilters:
    # Exclude base64-encoded content from incoming requests.
    json-path: {'$.bodyInformation.body' : '[base64]', '$.attachments[*].body': '[base64]'}
    # Exclude base64-encoded content from traffic to/from skatteverket
    x-path: {'//Body/text()':'[base64]', '//SignatureValue/text()':'[base64]', '//X509Certificate/text()':'[base64]'}
