spring: 
  application: 
    name: api-digitalmailsender
  datasource: 
    driverClassName: org.mariadb.jdbc.Driver
  flyway: 
    enabled: false

# OpenAPI
openapi:
  name: ${spring.application.name}
  title: Digital Mail Sender
  version: '@project.version@'

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: always

# Integrations
integration:
  # Skatteverket integration
  skatteverket:
    # Max size in bytes for the outgoing SOAP-envelope (2MB)
    message-max-size: 2097152
    # Which suppliers we support
    supported-suppliers:
      - kivra
      - minmyndighetspost
      - billo
      - fortnox

# Schedulers
scheduler:
  certificateHealth:
    name: certificate-health
    lockAtMostFor: PT2M
    maximumExecutionTime: PT2M
        
# Logging
logbook:
  body-filters:
    # Exclude BASE64-encoded content from requests.
    jsonPath:
      - key: '$.bodyInformation.body'
        value : '[base64]'
      - key: '$.attachments[*].body'
        value : '[base64]'
      - key: '$.files[*].body'
        value : '[base64]'
      - key: '$.parts[*].data'
        value : '[base64]'
    # Exclude BASE64-encoded content from traffic to/from skatteverket
    xPath:
      - key: '//SignatureValue/text()'
        value: '[base64]'
      - key: '//X509Certificate/text()'
        value: '[base64]'
      - key: '//Message/Attachment[Filename]/Body/text()'
        value: '[base64]'
      - key: '//Message/Body/Body/text()'
        value: '[base64]'
