name: "Call Dependabot reviewer"

on:
  pull_request_target:
  workflow_dispatch: # for testing purpose

permissions:
  pull-requests: write
  contents: write

jobs:
  shared-workflows:
    uses: Sundsvallskommun/.github/.github/workflows/common-dependabot-reviewer.yml@main
    secrets: inherit
