name: "Call Java CI with Maven"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    # At 11:02 on every day (Please note: GitHub actions schedule is in UTC time).
    - cron: "2 11 * * *"

jobs:
  shared-workflows:
    uses: Sundsvallskommun/.github/.github/workflows/java-maven-ci.yml@main
